name: WinGet submission on release
# based off of https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit Nstr.Igitt package to WinGet
        run: |

          $wingetPackage = "Nstr.Igitt"
          $gitToken = "${{ secrets.NSTR_WINGET_TOKEN }}"

          $github = Invoke-RestMethod -uri "https://api.github.com/repos/nstr-dev/igitt/releases" -Authentication Bearer -Token ($gitToken | ConvertTo-SecureString -AsPlainText)

          $targetRelease = $github | Where-Object -Property name -match 'v'| Select -First 1
          $installerUrl = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'igitt-setup-windows-amd64' | Select -ExpandProperty browser_download_url
          $ver = $targetRelease.tag_name

          # getting latest wingetcreate file
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update $wingetPackage -s -v $ver -u "$installerUrl" -t $gitToken
